use std::collections::HashMap;

use serde::{Deserialize, Serialize};

#[derive(Debug, Deserialize, Serialize)]
pub struct SlurmData {
    pub meta: SlurmMeta,
    pub jobs: Vec<SlurmJob>,
    pub warnings: Vec<String>,
    pub errors: Vec<String>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct SlurmMeta {
    pub command: Vec<String>,
    pub plugins: HashMap<String, String>,
    #[serde(rename = "Slurm")]
    pub slurm: SlurmMetaSlurm,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct SlurmMetaSlurm {
    pub version: HashMap<String, i32>,
    pub release: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct SlurmJob {
    pub account: String,
    pub accrue_time: i64,
    pub admin_comment: String,
    pub allocating_node: String,
    pub array_job_id: SlurmSetInfiniteNumberContainer,
    pub array_task_id: SlurmSetInfiniteNumberContainer,
    pub array_max_tasks: SlurmSetInfiniteNumberContainer,
    pub array_task_string: String,
    pub association_id: i16,
    pub batch_features: String,
    pub batch_flag: bool,
    pub batch_host: String,
    pub flags: Vec<String>,
    pub burst_buffer: String,
    pub burst_buffer_state: String,
    pub cluster: String,
    pub cluster_features: String,
    pub command: String,
    pub comment: String,
    pub container: String,
    pub container_id: String,
    pub contiguous: bool,
    pub core_spec: i16,
    pub thread_spec: i16,
    pub cores_per_socket: SlurmSetInfiniteNumberContainer,
    pub billable_tres: SlurmSetInfiniteNumberContainer,
    pub cpus_per_task: SlurmSetInfiniteNumberContainer,
    pub cpu_frequency_minimum: SlurmSetInfiniteNumberContainer,
    pub cpu_frequency_maximum: SlurmSetInfiniteNumberContainer,
    pub cpu_frequency_governor: SlurmSetInfiniteNumberContainer,
    pub cpus_per_tres: String,
    pub cron: String,
    pub deadline: i32,
    pub delay_boot: SlurmSetInfiniteNumberContainer,
    pub dependency: String,
    pub derived_exit_code: SlurmSetInfiniteNumberContainer,
    pub eligible_time: u64,
    pub end_time: u64,
    pub excluded_nodes: String,
    pub exit_code: SlurmSetInfiniteNumberContainer,
    pub extra: String,
    pub failed_node: String,
    pub features: String,
    pub federation_origin: String,
    pub federation_siblings_active: String,
    pub federation_siblings_viable: String,
    pub gres_detail: Vec<String>,
    pub group_id: i64,
    pub group_name: String,
    pub het_job_id: SlurmSetInfiniteNumberContainer,
    pub het_job_id_set: String,
    pub het_job_offset: SlurmSetInfiniteNumberContainer,
    pub job_id: u64,
    pub job_resources: Option<SlurmJobResources>,
    pub job_size_str: Vec<String>,
    pub job_state: String,
    pub last_sched_evaluation: u64,
    pub licenses: String,
    pub mail_type: Vec<String>,
    pub mail_user: String,
    pub max_cpus: SlurmSetInfiniteNumberContainer,
    pub max_nodes: SlurmSetInfiniteNumberContainer,
    pub mcs_label: String,
    pub memory_per_tres: String,
    pub name: String,
    pub network: String,
    pub nodes: String,
    pub nice: i16,
    pub tasks_per_core: SlurmSetInfiniteNumberContainer,
    pub tasks_per_tres: SlurmSetInfiniteNumberContainer,
    pub tasks_per_node: SlurmSetInfiniteNumberContainer,
    pub tasks_per_socket: SlurmSetInfiniteNumberContainer,
    pub tasks_per_board: SlurmSetInfiniteNumberContainer,
    pub cpus: SlurmSetInfiniteNumberContainer,
    pub node_count: SlurmSetInfiniteNumberContainer,
    pub tasks: SlurmSetInfiniteNumberContainer,
    pub partition: String,
    pub prefer: String,
    pub memory_per_cpu: SlurmSetInfiniteNumberContainer,
    pub memory_per_node: SlurmSetInfiniteNumberContainer,
    pub minimum_cpus_per_node: SlurmSetInfiniteNumberContainer,
    pub minimum_tmp_disk_per_node: SlurmSetInfiniteNumberContainer,
    pub power: HashMap<String, Vec<String>>,
    pub preempt_time: i16,
    pub preemptable_time: i16,
    pub pre_sus_time: i16,
    pub hold: bool,
    pub priority: SlurmSetInfiniteNumberContainer,
    pub profile: Vec<String>,
    pub qos: String,
    pub reboot: bool,
    pub required_nodes: String,
    pub minimum_switches: i16,
    pub requeue: bool,
    pub resize_time: i16,
    pub restart_cnt: i16,
    pub resv_name: String,
    pub scheduled_nodes: String,
    pub selinux_context: String,
    pub shared: Vec<String>,
    pub exclusive: Vec<String>,
    pub oversubscribe: bool,
    pub show_flags: Vec<String>,
    pub sockets_per_board: i16,
    pub sockets_per_node: SlurmSetInfiniteNumberContainer,
    pub start_time: u64,
    pub state_description: String,
    pub state_reason: String,
    pub standard_error: String,
    pub standard_input: String,
    pub standard_output: String,
    pub submit_time: u64,
    pub suspend_time: i16,
    pub system_comment: String,
    // INFO: the Number here is stored in minutes
    pub time_limit: SlurmSetInfiniteNumberContainer,
    pub time_minimum: SlurmSetInfiniteNumberContainer,
    pub threads_per_core: SlurmSetInfiniteNumberContainer,
    pub tres_bind: String,
    pub tres_freq: String,
    pub tres_per_job: String,
    pub tres_per_node: String,
    pub tres_per_socket: String,
    pub tres_per_task: String,
    pub tres_req_str: String,
    pub tres_alloc_str: String,
    pub user_id: u64,
    pub user_name: String,
    pub maximum_switch_wait_time: i16,
    pub wckey: String,
    pub current_working_directory: String,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct SlurmSetInfiniteNumberContainer {
    pub set: bool,
    pub infinite: bool,
    pub number: f32,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct SlurmJobResources {
    pub nodes: Option<String>,
    pub allocated_cores: Option<i16>,
    pub allocated_cpus: Option<i16>,
    pub allocated_hosts: Option<i16>,
    pub allocated_nodes: Option<Vec<SlurmAllocatedNodes>>,
}

#[derive(Debug, Serialize, Deserialize)]
pub struct SlurmAllocatedNodes {
    pub sockets: HashMap<String, HashMap<String, HashMap<String, String>>>,
    pub nodename: String,
    pub cpus_used: i16,
    pub memory_used: i64,
    pub memory_allocated: i64,
}
