name: Build SlurmHelper 
on: [push, pull_request]
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v4


      - name: Install rust
        uses: dtolnay/rust-toolchain@stable

      - name: Build
        run: cargo build --release
